"""NBA team stats for 2023-24 season."""

# Stats are based on 2023-24 season as of February 2024
NBA_TEAM_STATS = {
    'Boston Celtics': {
        'wins': 45,
        'losses': 12,
        'points_per_game': 121.2,
        'points_allowed': 109.8,
        'offensive_rating': 122.1,
        'defensive_rating': 110.7,
        'field_goal_pct': 48.9,
        'three_point_pct': 38.2,
        'home_record': {'wins': 26, 'losses': 3},
        'away_record': {'wins': 19, 'losses': 9},
        'last_ten': {'wins': 8, 'losses': 2, 'points_per_game': 122.5, 'points_allowed': 108.3}
    },
    'Milwaukee Bucks': {
        'wins': 35,
        'losses': 21,
        'points_per_game': 120.8,
        'points_allowed': 117.2,
        'offensive_rating': 119.8,
        'defensive_rating': 116.2,
        'field_goal_pct': 49.2,
        'three_point_pct': 37.8,
        'home_record': {'wins': 21, 'losses': 8},
        'away_record': {'wins': 14, 'losses': 13},
        'last_ten': {'wins': 5, 'losses': 5, 'points_per_game': 119.5, 'points_allowed': 118.2}
    },
    'Denver Nuggets': {
        'wins': 36,
        'losses': 19,
        'points_per_game': 116.5,
        'points_allowed': 111.8,
        'offensive_rating': 118.2,
        'defensive_rating': 113.5,
        'field_goal_pct': 49.5,
        'three_point_pct': 37.5,
        'home_record': {'wins': 20, 'losses': 6},
        'away_record': {'wins': 16, 'losses': 13},
        'last_ten': {'wins': 7, 'losses': 3, 'points_per_game': 117.8, 'points_allowed': 110.2}
    },
    'LA Clippers': {
        'wins': 36,
        'losses': 17,
        'points_per_game': 118.2,
        'points_allowed': 112.5,
        'offensive_rating': 119.5,
        'defensive_rating': 113.8,
        'field_goal_pct': 48.8,
        'three_point_pct': 38.5,
        'home_record': {'wins': 19, 'losses': 8},
        'away_record': {'wins': 17, 'losses': 9},
        'last_ten': {'wins': 8, 'losses': 2, 'points_per_game': 119.8, 'points_allowed': 111.5}
    },
    'Minnesota Timberwolves': {
        'wins': 39,
        'losses': 16,
        'points_per_game': 113.5,
        'points_allowed': 107.2,
        'offensive_rating': 115.8,
        'defensive_rating': 109.5,
        'field_goal_pct': 48.2,
        'three_point_pct': 37.2,
        'home_record': {'wins': 20, 'losses': 7},
        'away_record': {'wins': 19, 'losses': 9},
        'last_ten': {'wins': 7, 'losses': 3, 'points_per_game': 114.2, 'points_allowed': 106.8}
    },
    'Oklahoma City Thunder': {
        'wins': 37,
        'losses': 17,
        'points_per_game': 120.8,
        'points_allowed': 113.2,
        'offensive_rating': 120.5,
        'defensive_rating': 112.9,
        'field_goal_pct': 49.8,
        'three_point_pct': 38.8,
        'home_record': {'wins': 19, 'losses': 8},
        'away_record': {'wins': 18, 'losses': 9},
        'last_ten': {'wins': 7, 'losses': 3, 'points_per_game': 121.5, 'points_allowed': 112.8}
    },
    'Cleveland Cavaliers': {
        'wins': 36,
        'losses': 17,
        'points_per_game': 115.2,
        'points_allowed': 110.5,
        'offensive_rating': 116.8,
        'defensive_rating': 112.1,
        'field_goal_pct': 47.8,
        'three_point_pct': 36.5,
        'home_record': {'wins': 20, 'losses': 7},
        'away_record': {'wins': 16, 'losses': 10},
        'last_ten': {'wins': 9, 'losses': 1, 'points_per_game': 116.8, 'points_allowed': 109.2}
    },
    'Phoenix Suns': {
        'wins': 33,
        'losses': 22,
        'points_per_game': 117.8,
        'points_allowed': 115.2,
        'offensive_rating': 118.5,
        'defensive_rating': 115.9,
        'field_goal_pct': 48.5,
        'three_point_pct': 37.8,
        'home_record': {'wins': 18, 'losses': 10},
        'away_record': {'wins': 15, 'losses': 12},
        'last_ten': {'wins': 6, 'losses': 4, 'points_per_game': 118.2, 'points_allowed': 114.8}
    },
    'New York Knicks': {
        'wins': 33,
        'losses': 22,
        'points_per_game': 115.5,
        'points_allowed': 111.8,
        'offensive_rating': 116.2,
        'defensive_rating': 112.5,
        'field_goal_pct': 47.2,
        'three_point_pct': 36.8,
        'home_record': {'wins': 17, 'losses': 11},
        'away_record': {'wins': 16, 'losses': 11},
        'last_ten': {'wins': 6, 'losses': 4, 'points_per_game': 116.2, 'points_allowed': 112.5}
    },
    'Philadelphia 76ers': {
        'wins': 32,
        'losses': 22,
        'points_per_game': 116.8,
        'points_allowed': 112.5,
        'offensive_rating': 117.5,
        'defensive_rating': 113.2,
        'field_goal_pct': 47.8,
        'three_point_pct': 36.5,
        'home_record': {'wins': 18, 'losses': 9},
        'away_record': {'wins': 14, 'losses': 13},
        'last_ten': {'wins': 5, 'losses': 5, 'points_per_game': 115.8, 'points_allowed': 113.2}
    },
    'New Orleans Pelicans': {
        'wins': 33,
        'losses': 22,
        'points_per_game': 116.2,
        'points_allowed': 112.8,
        'offensive_rating': 117.8,
        'defensive_rating': 114.2,
        'field_goal_pct': 48.2,
        'three_point_pct': 37.2,
        'home_record': {'wins': 17, 'losses': 11},
        'away_record': {'wins': 16, 'losses': 11},
        'last_ten': {'wins': 7, 'losses': 3, 'points_per_game': 117.5, 'points_allowed': 111.8}
    },
    'Sacramento Kings': {
        'wins': 31,
        'losses': 23,
        'points_per_game': 118.5,
        'points_allowed': 117.2,
        'offensive_rating': 119.2,
        'defensive_rating': 117.9,
        'field_goal_pct': 47.8,
        'three_point_pct': 36.8,
        'home_record': {'wins': 16, 'losses': 11},
        'away_record': {'wins': 15, 'losses': 12},
        'last_ten': {'wins': 6, 'losses': 4, 'points_per_game': 119.2, 'points_allowed': 116.5}
    },
    'Indiana Pacers': {
        'wins': 31,
        'losses': 25,
        'points_per_game': 124.2,
        'points_allowed': 121.5,
        'offensive_rating': 123.8,
        'defensive_rating': 121.1,
        'field_goal_pct': 50.2,
        'three_point_pct': 38.2,
        'home_record': {'wins': 16, 'losses': 12},
        'away_record': {'wins': 15, 'losses': 13},
        'last_ten': {'wins': 5, 'losses': 5, 'points_per_game': 123.8, 'points_allowed': 122.2}
    },
    'Miami Heat': {
        'wins': 30,
        'losses': 25,
        'points_per_game': 112.5,
        'points_allowed': 111.8,
        'offensive_rating': 114.2,
        'defensive_rating': 113.5,
        'field_goal_pct': 46.8,
        'three_point_pct': 37.5,
        'home_record': {'wins': 15, 'losses': 12},
        'away_record': {'wins': 15, 'losses': 13},
        'last_ten': {'wins': 6, 'losses': 4, 'points_per_game': 113.2, 'points_allowed': 111.5}
    },
    'Orlando Magic': {
        'wins': 30,
        'losses': 25,
        'points_per_game': 112.8,
        'points_allowed': 111.2,
        'offensive_rating': 114.5,
        'defensive_rating': 112.9,
        'field_goal_pct': 47.2,
        'three_point_pct': 35.8,
        'home_record': {'wins': 16, 'losses': 12},
        'away_record': {'wins': 14, 'losses': 13},
        'last_ten': {'wins': 5, 'losses': 5, 'points_per_game': 113.5, 'points_allowed': 112.2}
    },
    'Dallas Mavericks': {
        'wins': 32,
        'losses': 23,
        'points_per_game': 118.8,
        'points_allowed': 117.5,
        'offensive_rating': 119.5,
        'defensive_rating': 118.2,
        'field_goal_pct': 48.2,
        'three_point_pct': 37.8,
        'home_record': {'wins': 17, 'losses': 11},
        'away_record': {'wins': 15, 'losses': 12},
        'last_ten': {'wins': 7, 'losses': 3, 'points_per_game': 119.5, 'points_allowed': 116.8}
    },
    'Los Angeles Lakers': {
        'wins': 30,
        'losses': 26,
        'points_per_game': 117.2,
        'points_allowed': 117.8,
        'offensive_rating': 116.8,
        'defensive_rating': 117.4,
        'field_goal_pct': 48.5,
        'three_point_pct': 36.2,
        'home_record': {'wins': 17, 'losses': 11},
        'away_record': {'wins': 13, 'losses': 15},
        'last_ten': {'wins': 5, 'losses': 5, 'points_per_game': 116.8, 'points_allowed': 118.2}
    },
    'Golden State Warriors': {
        'wins': 27,
        'losses': 26,
        'points_per_game': 118.5,
        'points_allowed': 117.8,
        'offensive_rating': 117.2,
        'defensive_rating': 116.5,
        'field_goal_pct': 47.8,
        'three_point_pct': 37.5,
        'home_record': {'wins': 16, 'losses': 11},
        'away_record': {'wins': 11, 'losses': 15},
        'last_ten': {'wins': 7, 'losses': 3, 'points_per_game': 119.2, 'points_allowed': 116.5}
    },
    'Houston Rockets': {
        'wins': 24,
        'losses': 31,
        'points_per_game': 113.8,
        'points_allowed': 114.5,
        'offensive_rating': 114.2,
        'defensive_rating': 114.9,
        'field_goal_pct': 46.8,
        'three_point_pct': 35.8,
        'home_record': {'wins': 17, 'losses': 11},
        'away_record': {'wins': 7, 'losses': 20},
        'last_ten': {'wins': 4, 'losses': 6, 'points_per_game': 114.2, 'points_allowed': 115.8}
    },
    'Brooklyn Nets': {
        'wins': 21,
        'losses': 33,
        'points_per_game': 112.5,
        'points_allowed': 115.8,
        'offensive_rating': 113.2,
        'defensive_rating': 116.5,
        'field_goal_pct': 46.5,
        'three_point_pct': 36.2,
        'home_record': {'wins': 12, 'losses': 16},
        'away_record': {'wins': 9, 'losses': 17},
        'last_ten': {'wins': 3, 'losses': 7, 'points_per_game': 111.8, 'points_allowed': 116.5}
    },
    'Atlanta Hawks': {
        'wins': 24,
        'losses': 31,
        'points_per_game': 119.2,
        'points_allowed': 121.5,
        'offensive_rating': 118.8,
        'defensive_rating': 121.1,
        'field_goal_pct': 46.8,
        'three_point_pct': 36.5,
        'home_record': {'wins': 14, 'losses': 14},
        'away_record': {'wins': 10, 'losses': 17},
        'last_ten': {'wins': 4, 'losses': 6, 'points_per_game': 118.5, 'points_allowed': 122.2}
    },
    'Toronto Raptors': {
        'wins': 19,
        'losses': 36,
        'points_per_game': 113.2,
        'points_allowed': 116.8,
        'offensive_rating': 114.5,
        'defensive_rating': 118.1,
        'field_goal_pct': 47.2,
        'three_point_pct': 35.5,
        'home_record': {'wins': 11, 'losses': 17},
        'away_record': {'wins': 8, 'losses': 19},
        'last_ten': {'wins': 3, 'losses': 7, 'points_per_game': 112.8, 'points_allowed': 117.5}
    },
    'Memphis Grizzlies': {
        'wins': 20,
        'losses': 36,
        'points_per_game': 108.5,
        'points_allowed': 114.2,
        'offensive_rating': 109.8,
        'defensive_rating': 115.5,
        'field_goal_pct': 44.8,
        'three_point_pct': 34.8,
        'home_record': {'wins': 11, 'losses': 17},
        'away_record': {'wins': 9, 'losses': 19},
        'last_ten': {'wins': 4, 'losses': 6, 'points_per_game': 109.2, 'points_allowed': 115.8}
    },
    'Portland Trail Blazers': {
        'wins': 15,
        'losses': 39,
        'points_per_game': 109.2,
        'points_allowed': 116.5,
        'offensive_rating': 110.5,
        'defensive_rating': 117.8,
        'field_goal_pct': 44.5,
        'three_point_pct': 35.2,
        'home_record': {'wins': 8, 'losses': 19},
        'away_record': {'wins': 7, 'losses': 20},
        'last_ten': {'wins': 2, 'losses': 8, 'points_per_game': 108.8, 'points_allowed': 117.2}
    },
    'Chicago Bulls': {
        'wins': 26,
        'losses': 29,
        'points_per_game': 111.8,
        'points_allowed': 114.5,
        'offensive_rating': 112.5,
        'defensive_rating': 115.2,
        'field_goal_pct': 46.2,
        'three_point_pct': 36.2,
        'home_record': {'wins': 15, 'losses': 13},
        'away_record': {'wins': 11, 'losses': 16},
        'last_ten': {'wins': 5, 'losses': 5, 'points_per_game': 112.2, 'points_allowed': 115.8}
    },
    'Utah Jazz': {
        'wins': 26,
        'losses': 29,
        'points_per_game': 117.8,
        'points_allowed': 119.5,
        'offensive_rating': 118.5,
        'defensive_rating': 120.2,
        'field_goal_pct': 47.2,
        'three_point_pct': 36.8,
        'home_record': {'wins': 17, 'losses': 11},
        'away_record': {'wins': 9, 'losses': 18},
        'last_ten': {'wins': 4, 'losses': 6, 'points_per_game': 116.8, 'points_allowed': 120.5}
    },
    'Charlotte Hornets': {
        'wins': 13,
        'losses': 41,
        'points_per_game': 108.2,
        'points_allowed': 117.8,
        'offensive_rating': 109.5,
        'defensive_rating': 119.1,
        'field_goal_pct': 45.2,
        'three_point_pct': 35.5,
        'home_record': {'wins': 7, 'losses': 20},
        'away_record': {'wins': 6, 'losses': 21},
        'last_ten': {'wins': 3, 'losses': 7, 'points_per_game': 107.8, 'points_allowed': 118.5}
    },
    'Washington Wizards': {
        'wins': 9,
        'losses': 45,
        'points_per_game': 112.5,
        'points_allowed': 122.8,
        'offensive_rating': 113.8,
        'defensive_rating': 124.1,
        'field_goal_pct': 46.5,
        'three_point_pct': 35.8,
        'home_record': {'wins': 5, 'losses': 22},
        'away_record': {'wins': 4, 'losses': 23},
        'last_ten': {'wins': 2, 'losses': 8, 'points_per_game': 111.8, 'points_allowed': 123.5}
    },
    'San Antonio Spurs': {
        'wins': 11,
        'losses': 44,
        'points_per_game': 111.2,
        'points_allowed': 120.5,
        'offensive_rating': 112.5,
        'defensive_rating': 121.8,
        'field_goal_pct': 45.8,
        'three_point_pct': 35.2,
        'home_record': {'wins': 6, 'losses': 21},
        'away_record': {'wins': 5, 'losses': 23},
        'last_ten': {'wins': 3, 'losses': 7, 'points_per_game': 110.8, 'points_allowed': 121.2}
    },
    'Detroit Pistons': {
        'wins': 8,
        'losses': 46,
        'points_per_game': 110.8,
        'points_allowed': 121.2,
        'offensive_rating': 111.5,
        'defensive_rating': 121.9,
        'field_goal_pct': 46.2,
        'three_point_pct': 35.5,
        'home_record': {'wins': 4, 'losses': 23},
        'away_record': {'wins': 4, 'losses': 23},
        'last_ten': {'wins': 2, 'losses': 8, 'points_per_game': 109.5, 'points_allowed': 122.5}
    }
}
